version: "3"

services:
  nginx:
    image: edukandalski/nginx:alpine
    build:
      context: nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s /docker-entrypoint.sh nginx -g "daemon off;"
    tty: true
    restart: always
    networks:
      - frontend-net
    depends_on:
      - app
    ports:
      - 8000:80

  app:
    image: edukandalski/node:15-alpine
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    tty: true
    restart: always
    networks:
      - backend-net
      - frontend-net
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge
